# Generated by Django 3.2.7 on 2021-12-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='inboxID',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='InboxObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox', max_length=100)),
                ('object', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
