# Generated by Django 3.2.7 on 2021-12-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211205_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
